### PR TITLE
Remove inner spacing

### PR DESCRIPTION
**Pull request by eduarenas80**
@confucious - review

### CODE REVIEW

**Comment by confucious** [comment]
Hmm. Seems ok but wonder if it'd be better to expose this as a property. .

**Comment by eduarenas80** [comment]
I thought about it, but it really seems like the only place this was actually used was for the partner logos in team create. Waij reduced the size of those assets and now the extra padding is unwanted. Do you think it's still worth it?

**Comment by confucious** [comment]
The library is meant to be reusable so hard coding a behavior like this for our use would seem to violate that goal. The alternative would be to subclass to be able to change behavior in gcios but I don't think we expose this in a good way for that.

**Comment by eduarenas80** [comment]
I guess that makes sense, I'll make it a property. It just seemed like that spacing was a hack to account for our weirdly proportioned partner logos in the first place, not something that should be part of it.

**Comment by eduarenas80** [comment]
Two things:

1) I was converting inner spacing to a property, and hit a roadblock because that constant was used in a class method. That means it would need to be a static variable, which seems terrible taking into account that we use this all over the place. I kind of feel like it's better to just get rid of it, as it was there only to make room some disproportionate logos that we don't use any more.

2) I accidentally pushed a commit in `GCMItemSelectTableViewDataSource.m ` that was supposed to be on a different PR.... could you review that on this branch?

**Comment by eduarenas80** [comment]
In case you feel very strongly about not losing the inner spacing, I have a comma ready to push that handles that by making it an argument the class methods that use it, but I think it just creates noise without providing much value

**Comment by confucious** [comment]
Ok, let's just kill the spacing in that case. Like Waijee kind of brought up, the styling needs a rethink and some independence from the rest of this code.

**Pull request merged**
